# Generated by Django 4.1.4 on 2022-12-26 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_to_api', models.URLField()),
                ('title', models.CharField(max_length=256)),
            ],
        ),
    ]
